import {
  EXPO_REACT_NATIVE_SERVER_URL,
  EXPO_REACT_NATIVE_SERVER_PORT,
} from "@env";

console.log(EXPO_REACT_NATIVE_SERVER_URL);
console.log(EXPO_REACT_NATIVE_SERVER_PORT);

export default {
  API_URL: `${EXPO_REACT_NATIVE_SERVER_URL}:${EXPO_REACT_NATIVE_SERVER_PORT}`,
};
